name: Deploying
on:
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Install gpg
      #   run: brew install gnupg

      # - name: Setup provisioning profile
      #   env:
      #     CERT_PASSPHRASE: ${{ secrets.CERT_PASSPHRASE }}
      #     PROFILE_PASSPHRASE: ${{ secrets.PROFILE_PASSPHRASE }}
      #   run: ./.github/scripts/decrypt_secrets.sh

      - name: Echo 1
        run: echo ${{ github.event.pull_request }}

      - name: Echo 2
        run: echo ${{ github.event.issue }}

      - name: Echo 2
        run: echo ${{ github.event.pull_request.number }}

      # - name: Update bundle version
      #   env:
      #     PR_NUMBER: ${{ github.event.issue.number }}
      #   run: ./.github/scripts/update_bundle_version.sh

      # - name: Archiving project
      #   run: ./.github/scripts/archive_app.sh

      # - name: Exporting .ipa
      #   run: ./.github/scripts/export_ipa.sh

      # - name: Publishing app
      #   if: success()
      #   env:
      #     APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
      #     APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
      #   run: ./.github/scripts/publish_testflight.sh